global:
  scrape_interval: 15s

scrape_configs:
  # 1️⃣ Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "172.17.0.2:9090"

  # 2️⃣ Website health check (google.com)
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://prometheus.io/
          - https://google.com/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.21.0.2:9115

  # 3️⃣ Jenkins monitoring
  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets:
          - "172.19.0.3:8080"